# Generated by Django 3.2.12 on 2022-03-28 17:20

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('apikey', models.UUIDField(default=uuid.uuid4)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('agreement_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('apikey', models.UUIDField(default=uuid.uuid4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('wallet_address', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='RequestorAgent',
            fields=[
                ('requestor_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=42)),
                ('node_name', models.CharField(blank=True, max_length=128, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderNode',
            fields=[
                ('node_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('node_name', models.CharField(blank=True, max_length=128, null=True)),
                ('subnet', models.CharField(max_length=128)),
                ('linked_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('network', models.IntegerField()),
                ('nonce', models.BigIntegerField()),
                ('sender', models.CharField(max_length=42)),
                ('yagna_time_created', models.DateTimeField()),
                ('yagna_time_last_action', models.DateTimeField()),
                ('yagna_time_sent', models.DateTimeField()),
                ('yagna_time_confirmed', models.DateTimeField()),
                ('yagna_starting_gas_price', models.CharField(default=None, max_length=128, null=True)),
                ('yagna_maximum_gas_price', models.CharField(default=None, max_length=128, null=True)),
                ('yagna_status', models.IntegerField()),
                ('final_tx', models.CharField(max_length=70, unique=True)),
                ('recipient', models.CharField(default=None, max_length=42, null=True)),
                ('gas_used', models.IntegerField(default=None, null=True)),
                ('gas_limit', models.IntegerField(default=None, null=True)),
                ('gas_price', models.CharField(default=None, max_length=128, null=True)),
                ('amount_human', models.FloatField(default=None, null=True)),
                ('gas_spent_human', models.FloatField(default=None, null=True)),
                ('gas_price_gwei', models.FloatField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=128)),
                ('issuer_id', models.CharField(max_length=42)),
                ('payment_platform', models.CharField(max_length=64)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agreement')),
                ('linked_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.AddField(
            model_name='agreement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='provider_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.providernode'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.UUIDField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=64)),
                ('job_quantity', models.FloatField()),
                ('job_unit', models.CharField(max_length=64)),
                ('cpu_time', models.FloatField()),
                ('job_cost', models.FloatField()),
                ('task_status', models.CharField(max_length=64)),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agreement')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.invoice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('provider_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.providernode')),
                ('requestor_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requestoragent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('network', 'nonce', 'sender'), name='primary_transaction_triple'),
        ),
    ]
