# Generated by Django 3.2.12 on 2022-03-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gasPrice',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gasUsed',
            field=models.BigIntegerField(),
        ),
    ]
