# Generated by Django 3.2.12 on 2022-03-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providernode',
            old_name='provider',
            new_name='linked_provider',
        ),
        migrations.RenameField(
            model_name='providernode',
            old_name='providerId',
            new_name='provider_id',
        ),
    ]
