# Generated by Django 3.2.12 on 2022-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220329_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='amount_accepted',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='activity',
            name='amount_due',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='activity',
            name='amount_paid',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='activity',
            name='amount_scheduled',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
