# Generated by Django 3.2.12 on 2022-03-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220317_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gasPrice',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gasPriceGwei',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gasUsed',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='glm',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='matic',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient',
            field=models.CharField(default=None, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender',
            field=models.CharField(default=None, max_length=42, null=True),
        ),
    ]
