# Generated by Django 3.2.12 on 2022-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220406_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='approved_ts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='creation_ts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='demand_constraints',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='demand_properties',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='offer_constraints',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='offer_properties',
            field=models.JSONField(default='{}'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='state',
            field=models.CharField(default='UNKNOWN', max_length=64),
        ),
        migrations.AddField(
            model_name='agreement',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
