# Generated by Django 3.2.12 on 2022-04-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220406_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='usage_cost',
            field=models.JSONField(default='{}'),
        ),
    ]
