# Generated by Django 3.2.12 on 2022-03-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='tx',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
