# Generated by Django 3.2.13 on 2022-05-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='user',
        ),
    ]
