#Location: .github/workflows/custom_config.yml

name: Build and push containers to Dockerhub
env:
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Git clone on our repo
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        run: make login

      - name: Build Containers
        run: make build-amd64

      - name: Push Containers
        run: make push-amd64


      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
                docker service update --force --image phillipjensen/payment-monitor-backend:${{ github.sha }} payments_django
                docker service update --force --image phillipjensen/payment-monitor-backend-celery:${{ github.sha }} payments_celery
                docker service update --force --image phillipjensen/payment-monitor-backend-celery-beat:${{ github.sha }} payments_celery_beat
  
  